openapi: 3.0.1
info:
  title: Aggregate1
  description: API Definition of Aggregate1
  version: 1.0.0
servers:
- url: http://localhost:8290/aggregate1
paths:
  /:
    get:
      responses:
        default:
          description: Default response
