openapi: 3.0.1
info:
  title: Aggregate
  description: API Definition of Aggregate
  version: 1.0.0
servers:
- url: http://localhost:8290/aggregate
paths:
  /:
    get:
      responses:
        default:
          description: Default response
