openapi: 3.0.1
info:
  title: Contract_Soap
  description: API Definition of Contract_Soap
  version: 1.0.0
servers:
- url: http://localhost:8290/Contract_Soap
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
