openapi: 3.0.1
info:
  title: ConvertJsontoXml
  description: API Definition of ConvertJsontoXml
  version: 1.0.0
servers:
- url: http://localhost:8290/ConvertJsontoXml
paths:
  /:
    get:
      responses:
        default:
          description: Default response
