openapi: 3.0.1
info:
  title: CusConClone_soap
  description: API Definition of CusConClone_soap
  version: 1.0.0
servers:
- url: http://localhost:8290/CusConClone_soap
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
