openapi: 3.0.1
info:
  title: Customer_Soap
  description: API Definition of Customer_Soap
  version: 1.0.0
servers:
- url: http://localhost:8290/Customer_Soap
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
