openapi: 3.0.1
info:
  title: DBLookUp
  description: API Definition of DBLookUp
  version: 1.0.0
servers:
- url: http://localhost:8290/dblookup
paths:
  /:
    get:
      responses:
        default:
          description: Default response
