openapi: 3.0.1
info:
  title: DBLookUp1
  description: API Definition of DBLookUp1
  version: 1.0.0
servers:
- url: http://localhost:8290/dbllokup1
paths:
  /:
    get:
      responses:
        default:
          description: Default response
