openapi: 3.0.1
info:
  title: Drop
  description: API Definition of Drop
  version: 1.0.0
servers:
- url: http://localhost:8290/drop
paths:
  /:
    get:
      responses:
        default:
          description: Default response
