openapi: 3.0.1
info:
  title: Filter
  description: API Definition of Filter
  version: 1.0.0
servers:
- url: http://localhost:8290/filter
paths:
  /:
    get:
      responses:
        default:
          description: Default response
