openapi: 3.0.1
info:
  title: Iterative
  description: API Definition of Iterative
  version: 1.0.0
servers:
- url: http://localhost:8290/iterative
paths:
  /:
    get:
      responses:
        default:
          description: Default response
