openapi: 3.0.1
info:
  title: JavaCustomMediator
  description: API Definition of JavaCustomMediator
  version: 1.0.0
servers:
- url: http://localhost:8290/javacustommediator
paths:
  /:
    get:
      responses:
        default:
          description: Default response
