openapi: 3.0.1
info:
  title: LoopBack
  description: API Definition of LoopBack
  version: 1.0.0
servers:
- url: http://localhost:8290/loopback
paths:
  /:
    get:
      responses:
        default:
          description: Default response
