openapi: 3.0.1
info:
  title: Store
  description: API Definition of Store
  version: 1.0.0
servers:
- url: http://localhost:8290/store
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
