openapi: 3.0.1
info:
  title: storeapi
  description: API Definition of storeapi
  version: 1.0.0
servers:
- url: http://localhost:8290/storeapi
paths:
  /:
    post:
      responses:
        default:
          description: Default response
