openapi: 3.0.1
info:
  title: Sum
  description: API Definition of Sum
  version: 1.0.0
servers:
- url: http://localhost:8290/sum
paths:
  /:
    get:
      responses:
        default:
          description: Default response
