openapi: 3.0.1
info:
  title: Switch
  description: API Definition of Switch
  version: 1.0.0
servers:
- url: http://localhost:8290/switch
paths:
  /:
    post:
      responses:
        default:
          description: Default response
