openapi: 3.0.1
info:
  title: Test2
  description: API Definition of Test2
  version: 1.0.0
servers:
- url: http://localhost:8290/Test2
paths:
  /:
    get:
      responses:
        default:
          description: Default response
